### ISSUE TITLE
v1.3.8 (and probably v1.4.x) does not compile with Boost <1.66

### ISSUE THREAD

**Issue by dennisklein** [FairRootGroup/FairMQ#196]
Thx for the bug report to Gergely Debreczeni!

```
[ 15%] Building CXX object fairmq/CMakeFiles/FairMQ.dir/shmem/FairMQTransportFactorySHM.cxx.o

In file included from /usr/include/boost/process/detail/traits.hpp:11:0,
                 from /usr/include/boost/process/async.hpp:32,
                 from /usr/include/boost/process.hpp:23,
                 from /home/gdebrecz/works/FairMQ/fairmq/fairmq/shmem/FairMQTransportFactorySHM.cxx:15:
/usr/include/boost/process/detail/traits/async.hpp:15:7: error: using typedef-name ‘boost::asio::io_service’ after ‘class’
 class io_service;
       ^~~~~~~~~~
In file included from /home/gdebrecz/works/FairMQ/fairmq/fairmq/Tools.h:14:0,
                 from /home/gdebrecz/works/FairMQ/fairmq/fairmq/shmem/Manager.h:18,
                 from /home/gdebrecz/works/FairMQ/fairmq/fairmq/shmem/FairMQTransportFactorySHM.h:12,
                 from /home/gdebrecz/works/FairMQ/fairmq/fairmq/shmem/FairMQTransportFactorySHM.cxx:10:
/home/gdebrecz/works/FairMQ/fairmq/fairmq/tools/Network.h:22:26: note: ‘boost::asio::io_service’ has a previous declaration here
 typedef class io_context io_service;
                          ^~~~~~~~~~
In file included from /usr/include/boost/process/async.hpp:35:0,
```

Need to check if this also affects current `dev`.

**Comment by dennisklein** [comment]
`dev` is not affected since it [requires](#198) Boost >= `1.66`.
